# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/f5160794-3804-4e32-8c36-7c66c30758dd";
#      fsType = "btrfs";
#    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b1cfb306-c193-4c1e-9785-6eed6bc0d553"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
